:Title: OGC (add title text)
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: 2024-02-09
|Approval Date:   <yyyy-mm-dd>
|Internal reference number of this OGC(R) document:  24-003
|Category: OGC(R) Standards Working Group Charter
|Authors:   Nils Hempelmann ( OGC ), Rachel Opitz ( OGC ), Neil Sims (CSIRO), Allan Jamieson (Ordnance Survey)
|Contributors: Brian O’Conor (UNCCD), Steven Ramage (CEOS), Bernd Eversmann (GIZ), Gabriel Daldegan (CI)


|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) <year> Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

////
Version of 2018-12-12
Some Instructions
This document is the template to be used for proposing the formation of a new Standards Working Group (SWG).

The first step is to complete the SWG Charter for the proposed new SWG.

The next step is to email the draft SWG charter to the Technical Committee Chair (TCC).  The TCC will review the draft charter and make any necessary comments and provide guidance.

Finally, once the Charter is ready, the SWG charter will be posted to the OGC Pending Documents and the vote process in the Technical Committee Policies and Procedures will start.

Any questions, please contact OGC staff.
////

To: OGC members & interested parties

A new OGC Standards Working Group is being formed. The OGC members listed below have proposed the OGC <Name of SWG>.  The SWG proposal provided in this document meets the requirements of the OGC Technical Committee (TC) Policies and Procedures.

The SWG name, statement of purpose, scope, list of deliverables, audience, and language specified in the proposal will constitute the SWG's official charter. Technical discussions may occur no sooner than the SWG's first meeting.

This SWG will operate under the OGC IPR Policy. The eligibility requirements for becoming a participant in the SWG at the first meeting (see details below) are that:

* You must be an employee of an OGC member organization or an individual
member of OGC;

* The OGC member must have signed the OGC Membership agreement;

* You must notify the SWG chair of your intent to participate to the first meeting. Members may do so by logging onto the OGC Portal and navigating to the Observer page and clicking on the link for the SWG they wish to join and;

* You must attend meetings of the SWG. The first meeting of this SWG is at the time and date fixed below. Attendance may be by teleconference.

Of course, participants also may join the SWG at any time. The OGC and the SWG welcomes all interested parties.

Non-OGC members who wish to participate may contact us about joining the OGC. In addition, the public may access some of the resources maintained for each SWG: the SWG public description, the SWG Charter, Change Requests, and public comments, which will be linked from the SWG’s page.

Please feel free to forward this announcement to any other appropriate lists. The OGC is an open standards organization; we encourage your feedback.

== Purpose of the Standards Working Group

////
Proposers will describe the purpose of the Standards Working Group and its overall mission in relation to OGC processes, the OGC Standards baseline, and OGC’s business plan.
////

Policy initiatives over the last three decades have worked to limit the impacts of global warming, reverse land degradation, stop the loss of biodiversity, protect finite natural resources, and reduce risks associated with environmental disasters. Tracking progress toward achieving the aims of these initiatives is a complex task, requiring integrated work across multiple research domains, the deployment of data and technologies including sophisticated observation instruments and networks, and coordinated modelling experiments to continually improve the scientific state of the art. Globally interconnected data and analytical infrastructures based on open standards are essential to the success of this work because they enable the translation of raw geospatial data to reliable indicators used in benchmarking and decision-making.
The purpose of this SWG is 

* to develop a portfolio of open standards that enable the robust, transparent and consistent use of geospatial data and indicators in international reporting schemes and 
    
* to accelerate the development and adoption of open standards-based geospatial technologies that can form components of systems used to implement international reporting schemes, including systems supporting planning, data collection, monitoring and reporting activities. 

The standardisation promoted by this SWG will support transparency in international reporting indicators which rely on geospatial data (referred to as Geospatial Reporting Indicators), enable interoperability between local, national, and regional geospatial data infrastructures and analytical applications to facilitate reporting processes, and help build shared understandings of which approaches work in a range of global contexts through robust comparisons. The community consensus-based process used in the development of OGC standards and standards-based technologies will promote inclusiveness and representation of the global community in shaping geospatial reporting indicators.

There are many geospatial reporting indicators in use by international organizations, private sector consortia, and national governments, some of which are specific to one or more sectors, some which target a specific factor such as impacts of methane emissions, and some which cover multiple factors and are sector agnostic. To make progress, the GRI SWG plans to set an area of focus for one or more years, to be reviewed annually and voted on by the SWG committee. It is anticipated that the focus area will evolve over time in response to opportunities and progress made on standards development. An initial focus area is defined in section 3 of this charter.


== Business value proposition

////
This section provides a statement describing the value of this standards activity in relation to the OGC Membership, the geospatial community, and the wider IT community. This statement can be in terms of the interoperability problem being solved, processing Change requests to meet market (and Member requirements), a policy requirement and/or some other business value proposition. The proposition described in this section does not have to be in economic terms.
////

The market for services supporting reporting against global indicators has grown significantly over the past decade. The  https://www.cgfi.ac.uk/2023/03/state-and-trends-of-spatial-finance-2023/[“State and Trends of Spatial Finance 2023”] report from the Spatial Finance Initiative summarises a few key data points, noting: https://technation.io/report/climate-tech-report-2022/[“Tech Nation’s 2022 Climate Tech report] records 44,595 companies developing technology solutions to tackle the climate crisis, a four-fold increase since 2010, collectively raising $111bn in growth capital in 2021. CommerzVentures’ Climate Fintech report found that climate fintech start-ups raised $2.9bn in 2022, 2.4x more than in all of 2021.” Their report highlights physical climate risk analytics, environmental markets monitoring, reporting and verification (MRV) solutions, and nature and biodiversity analytics as strong growth areas. These trends are likely to be augmented by new schemes in the near term, notably including the extension of the https://environment.ec.europa.eu/topics/forests/deforestation/regulation-deforestation-free-products_en[EU’s Regulation on Deforestation-free Products] through intensified engagement with partner countries to launch the global “Team Europe Initiative on Deforestation-free Value Chains” with new financial support of EUR 70M, as announced in at COP28, together with https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fleginfo.legislature.ca.gov%2Ffaces%2FbillTextClient.xhtml%3Fbill_id%3D202320240SB253&data=05%7C01%7Cnatalie.runyon%40thomsonreuters.com%7Caaac6654281f46a8602c08dbcfe4ae62%7C62ccb8646a1a4b5d8e1c397dec1a8258%7C0%7C0%7C638332353318710626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lu3IMcojVmtht5RjXSfucg07rzSCQyMe01BOdI%2FQaAY%3D&reserved=0[California’s Climate Corporate Data Accountability Act] (SB 253) making climate emissions disclosure mandatory together with https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fleginfo.legislature.ca.gov%2Ffaces%2FbillTextClient.xhtml%3Fbill_id%3D202320240SB261&data=05%7C01%7Cnatalie.runyon%40thomsonreuters.com%7Caaac6654281f46a8602c08dbcfe4ae62%7C62ccb8646a1a4b5d8e1c397dec1a8258%7C0%7C0%7C638332353318710626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jBLxwEr3UALalDyUCKsGaVXUHVU%2F99LQve7Jd1wlzAs%3D&reserved=0['SB 261'], requiring climate-related financial risks disclosure.

The scale and growth of the market suggests significant global demand for geospatial services that support reporting against global schemes, both related to corporate financial disclosures and targets for progress against the United Nations Sustainable Development Goals (UN SDGs). However, at present, the lack of standardization in geospatial data makes it difficult to address potential greenwashing and ensure data integrity and accountability through robust diligence, monitoring and verification processes that rely on geospatial data. It is likewise challenging to analyze and compare risks to physical assets using diverse geospatial data to characterize their changing contexts over time. A key part of the business value proposition of this SWG is to transform data silos within reporting indicator applications into interoperable and federated collaborative solutions, enhancing the value chain and resulting information products. 

Beyond the financial value, the development of consensus-based standards for geospatial reporting indicators can help to realise significant public benefits. These public benefits may include increasing the confidence of communities in claims made by private and government organizations regarding actions taken to address climate change, leading to improved communication which in turn facilitates community engagement in decision making processes. They may also include improvements in the equity of assessments based on reporting indicators, again increasing public trust and improving a community’s sense of belonging and wellbeing. Better targeted interventions which deploy resources to the communities and landscapes where they are most needed can also provide these benefits.


== Initial focus

This SWG’s initial focus area is the standardization of geospatial reporting indicators associated with Land Degradation Neutrality (LDN), as defined in the United Nations Sustainable Development Goal (SDG) 15.3.1. LDN was prioritized as a focus area because work to achieve LDN acknowledges and facilitates a broad range of development activities by incorporating them into a whole-of-landscape land use planning framework that balances development with conservation and restoration activities to maintain or reduce the extent of degraded land. It therefore will enable this SWG to engage a diverse pool of stakeholders whose work’s scope includes LDN and may also include reporting under other frameworks. Demonstrably achieving Land Degradation Neutrality is valuable to national governments, together with regional governments, public agencies, and supporting organizations, because it helps countries meet their UN SDG commitments (specifically Target 15.3), providing an incentive for engagement by these stakeholders groups. 

A strong foundation for this initial focus area exists. Consortium building is well advanced, with significant international buy-in for LDN demonstrated at the recent LDN Global Dialogue Forum (Cape Town, October 2023), which attracted applications from 59 teams in 40 countries. Technical foundations have been set in place. Documentation of current data standards for geospatial data used in UNCCD national reporting was carried out through an analysis of the UNCCD reporting platform (Performance Review and Assessment of Implementation System (PRAIS). Coordination with the key domain organization driving the reporting indicator development has been agreed in principle. The work proposed under the GRI SWG will be coordinated with the next phase of the GEO-LDN Flagship initiative. The GEO-LDN Flagship will provide access to datasets and analytical tools to measure, plan and monitor LDN. Its objectives are to provide the LDN community with a ‘federated’ suite of datasets and analytical tools that enable users to appropriately assess land degradation consistent with the Good Practice Guidance (GPG), seamlessly transfer and translate results between phases of the integrated land use planning process, and monitor the effectiveness of remediation activities on land condition. Coordination of standards for data quality, and for the accessibility and function of analytical tools, are essential steps towards these objectives.

While some of the endeavours related to LDN have benefited from international coordination and funding under the umbrella of the UN 2030 Agenda for Sustainable Development, Land Degradation Neutrality (LDN) initiative, the Paris Agreement (PA) on climate change, the Sendai Framework for Disaster Risk Reduction (SFDRR) and other framework agreements, many still rely on uncoordinated national or international projects, resulting in a proliferation of incompatible, short-lived initiatives. This SWG is positioned to enhance the effectiveness of geospatial reporting indicators related to LDN to optimise the ongoing collaborative activity of the international community. The added value is meaningful: reducing wasted time and energy, discouraging the proliferation of solo technological initiatives all solving the same simple problems, and enabling work on more complex issues.  

Beyond the focus on data, underpinning information systems like Climate Resilience Information Systems (CRIS) can be operationalized more effectively when interoperability among the separate services are ensured. Realising this benefit requires standardisation of services following the FAIR principles (Findable, Accessible, Interoperable, Reusable). Beside FAIR the principles of TRUST (Transparency, Responsibility, User focus, Sustainability and Technology) and CARE principles for indigenous data governance  needs to be considered when standardising geospatial reporting indicators. 

Many national or regional climate resilience information systems (CRIS) are already operational, and the work of this SWG will enhance their capacity to provide a value chain from raw data to usable information. Development of GRI standards will also enable further nations and regions to develop compatible systems which leverage standardized GRIs for LDN planning, monitoring and reporting. Work on LDN related indicators will provide a starting point to develop appropriate framework standards and principles for a suite of Geospatial Reporting Indicators.

== Scope of work

The Scope of Work of the GRI SWG encompasses:

* Identification of core requirements for geospatial reporting indicators.  

* Standardization of geospatial reporting indicators used in assessments (measurement, monitoring, reporting and verification) related to international, national and sub-national policy frameworks. 

* Standardization of geospatial reporting indicators used in assessments (measurement, monitoring, reporting and verification) related to frameworks established by industry, NGOs, community and third sector organizations.

* Promotion of the development of data systems and technologies that incorporate or produce open standards-based geospatial reporting indicators. 

A detailed work program defining the scopes, beside the initial focus will be defined by the SWG under the lead of the elected chairs.   

=== Specific existing work used as starting point 

Geospatial Reporting Indicators need to be consistent with existing OGC standards and non-OGC standards. For the initial phase targeting LDN, the GEO-LDN Flagship has established data models to be taken into account as the basis for a documented and approved OGC standard developed by this SWG. The value chain from raw data to information usable in Reporting Indicators may draw on existing OGC APIs like:

* WCS: OGC Web Coverage Service can provide on-demand LDN data services for coverage data.
* WFS: OGC Web Feature Service can provide on-demand LDN data services for feature data.
* OGC API – Features can provide on-demand LDN data services for feature data.
* CSW: OGC Catalog Service for Web can provide federated discovery of LDN products from multiple data providers
* GML: GML is a comprehensive encoding of features, geometry, and topology in XML. GML can be used to encode the feature LDN.
* Geopackage and GeoJSON as these each have specific advantages over GML depending on the use case.
* GeoTIFF, NetCDF, and HDF5: These OGC standards are useful for encoding and packing coverage LDN
* WKT CRS: The Well-Known Text representation of Coordinate Reference Systems offers a standardized way to describe CRSs for reference by any spatial data set fully.
* Observations and Measurements: this standard defines XML schemas for observations, and for features involved in sampling when making observations. These provide document models for the exchange of information describing observation acts and their results, both within and between different scientific and technical communities.
* Several evolving OGC Standards are also relevant: OGC API – Tiles, OGC API – Maps, OGC API – Records, STAC, OGC API-EDR, OGC API-Processes and Cloud Optimized GeoTIFF.
* DGGS Abstract Specification: The goal of DGGS is to enable rapid assembly of spatial data without the difficulties of working with projected coordinate reference systems. DGGSs represent the Earth as hierarchical sequences of equal area tessellations, each with global coverage and with progressively finer spatial resolution.
* The following ISO TC211 Standards will be relevant in this work:

    - ISO 19115 - Metadata, parts 1-3. Underpinning the definition and management of metadata.
    - ISO 19131 - Data product specifications. A method of specifying a geospatial data product.
    - ISO 19157 - Data quality general requirements.
    - ISO 19144-1 - Classification systems structure.
    - ISO 19144-2 - Land cover meta language (LCML)
    - ISO 19144-3 - Land use meta language (LUML)
    - ISO 19144-4 - Registration and implementation
    - ISO 19110 - Feature catalogue
    - ISO 19111 - Reference by coordinates
    - ISO 19152-1 Land Administration Domain Model, Generic conceptual model
    - ISO 19152-2 LADM Land registration
    - ISO 19152-3 LADM Marine Georegulation
    - ISO 19152-4 LADM Valuation information
    - ISO 19152-5 LADM Spatial plan information
    - ISO 19152-6 LADM Implementation 

The work builds on the Analysis Ready Data (ARD) concepts developed and documented in the OGC-ARD-SWG and prior work on minimum requirements by the GeoLDN group. The SWG plans to adopt the OGC-ARD definition and tailor its scope to the data and tools required for the UNCCD reporting processes. 

The SWG will define standards that specify a set of minimum requirements, including but not limited to, the content, structure, organization, applied preprocessing, metadata, format, and naming conventions, that a type of geospatial data product shall be met for the value chain from raw data to LDN-information (SDG 15.3.1 indicator data) suitable for the UNCCD PRAIS data storage. 

The GRI SWG will build their work upon the concepts of e.g. essential land variables, essential biodiversity variables, essential agricultural variables etc. 

In its initial focus on LDN national reporting, the remit of the SWG is to build upon and  extend the consultation and recommendations provided for the data decision trees and existing work on standardising related processing tools carried out by the UNCCD and GEO-LDN Group. The technical standardisation of data and tools used in national UNCCD reporting mechanisms within the UN policy framework requires work in three key areas:
* Data structure: building on prior OGC work on JSON data structures, encoding standards, ARD concepts, and data structures proposed by trends.earth to formalize a ‘profile’ for the ARD standard which can be created for the specific needs of the GEO-LDN community.

* Application interoperability: Documenting the standard and application profile(s) developed to ensure interoperability of the tools required to implement processes for monitoring, planning and reporting on LDN. 

* Scalability: GEO-LDN data and systems will need to be useable in National, regional and local contexts as countries set their LDN targets and implement actions, therefore technologies, data systems and standards developed by this SWG in the first year must work across the full range of scales. 

Documenting the data and application standards for national reporting of the LDN mechanism based on the SDG indicator 15.3.1 provides a suitable starting point because the results can be transferred to other SDG indicators like SGD 15.4.2 Mountain Green Cover Index. The scope of the first phase of activity in the SWG will therefore include the exploration and realization to extend the LDN related SDG 15.3.1 standardization to other SDG indicators. 

Key to the broader scope of the SWG is the connection of established geospatial reporting indicators with standards applied in the context of ESG reporting. The GRI-SWG’s scope will therefore include the exploration of implementable options and challenges to enable the interoperability of reporting indicators between SDG and ESG-centric systems to create a coherent information value chain. 

== What is out of scope?

The aim of the SWG is not to create another general reporting indicator standard, but rather to standardize geospatial elements across the plethora of reporting indicators currently in use. Developing new reporting indicator systems is out of scope. 

In the first phase, the SWG will standardize the LDN concept and framework and define LDN Product Family Specifications (PFS) at data type level. Data-instance level LDN work will be out of scope. Scopes for future focus areas will be defined through a consensus-based debate and voting process. 


=== Is this a persistent SWG

[x] YES

[ ] NO

=== When can the SWG be inactivated

The focus area of the SWG will be reviewed and voted on annually. The SWG will be deactivated if no new substantial activities, i.e. progress on and production of standards, review of existing standards, voting to adopt standards, or establishment and operation of COSI pilots, occurs for a period of 3 years. If a chair resigns and a new chair cannot be identified within a period of 18 months, the SWG will be inactivated.

== Description of deliverables

In its first phase, focused on LDN, the SWG will deliver:

* A guide on using existing standards to spin off national-local-regional LDN information systems
* A draft OGC Standard on Geospatial UNCCD national reporting data 

The SWG will promote the establishment of a COSI Pilot to develop further deliverables including:

    - Improvements to interoperability solutions for the LDN Toolbox and related applications. 
    - A report on practical technical barriers and opportunities for building interoperable data systems that support geospatial reporting indicators used in planning, monitoring progress toward, and making interventions in support of Land Degradation Neutrality.


=== Initial deliverables

////
Describe the initial Standard(s) to be developed by the SWG.
////

The target start date for this SWG is the first half of 2024, once the charter is approved. The SWG will aim to deliver an initial release of the candidate Standard for review in the last quarter of 2024.
The following deliverables will be included in the initial results of the SWG:
OGC Standard: Geospatial UNCCD national reporting data – Part-1 – Fundamentals and Framework

We envision this OGC Geospatial LDN standard will be a multi-part standard with at least 6 parts, of which in the beginning the focus will be on 

    Part 1- Fundamentals and Framework

A possible structure for further parts could be:

    Part 2- Land Product Family Specification, 
    Part 3 – Coastal Erosion Product Family Specification, 
    Part 4 – Atmospheric Product Family Specification, 
    Part 5 – Earth System Model Output Product Family Specification, and 
    Part 6 – ARD Service Specification. However, other denominations are imaginable. 

The SWG will start to develop Part 2 of the standard when the draft of Part-1 is out for public review.

=== Additional SWG tasks

////
Describe each additional Standard to be developed by the SWG as an additional task after the deliverables from the initial charter have been completed. This section is blank in a new charter, then is populated with each task approval request per the OGC TC Policies and Procedures.
////

== IPR Policy for this SWG

[x] RAND-Royalty Free

[ ] RAND for fee

== Anticipated audience / participants

The SWG will be tasked with identifying a subsequent area of focus after the completion of LDN focused work.
The SWG will support COSI Pilots through review of engineering reports, guides for practitioners, impact reports and other documents and prototypes produced related to the LDN focused work.

== IPR Policy for this SWG

[x] RAND-Royalty Free
[ ] RAND for fee

== Anticipated audience / participants

This SWG aims to attract participants from a range of policy and industry-led reporting indicator communities. It is anticipated that the group’s initial composition will include a concentration of members interested in policy-led reporting and organizations connected to the UN reporting mechanisms, given the initial focus on LDN. 

This SWG will work closely with CEOS and its member agencies. Experts from the CEOS ARD Oversight Group as well as OGC members of space agencies, including NASA and ESA, will comprise the majority of the SWG. In addition, other geospatial data providers, geoscientists, computer scientists, software engineers from academia, industry, and government will be interested in assisting with the development of reporting indicators and the LDN Standard in the first instance through this SWG. 

== Domain Working Group endorsement

This draft charter will be presented to the Climate Resilience DWG with a request for endorsement.

== Other informative information about the work of this SWG

=== Collaboration

UNCCD: a key stakeholder community benefiting from the outcomes of the GRI-SWG, particularly in the first phase focused on data standards for the UNCCD national reporting through PRAIS

UN-GGIM: The IGIF Working Group of the UN-GGIM will be invited to collaborate with the GRI SWG as a coordinating group for nations implementing this framework.  They are actively mapping 17 SDGs https://www.un.org/geospatial/

CEOS: Through ESA, NASA and other space agencies. 

GEO Secretariat: POC to be identified 

GEO-LDN: particularly the Working groups on capacity building, data standardization and data processing.  It is envisioned that the majority of members of the OGC SWG will be the members of the corresponding GEO-LDN Working Group. 

WGIC: A representative will be invited to serve as a POC to coordinate with industry stakeholders through the WGIC as an umbrella organization. 

ISO-TC211: A representative will be invited to collaborate on the development of the draft OGC Standard on Geospatial UNCCD national reporting data. Furthermore they will be best placed to offer further advice on the future activities of the SWG, from an ISO point of view.

////
Describe the work environment of the SWG, including the use of GitHub or GitLab.
////

////
=== Similar or applicable standards work (OGC and elsewhere)

The following Standards and projects may be relevant to the SWG's planned work, although none currently provide the functionality anticipated by this committee's deliverables:

OASIS BPEL
IETF HTTP

The SWG intends to seek and if possible maintain liaison with each of the organizations maintaining the above works.
////

=== Details of first meeting

The SWG will meet two weeks after the approval of the charter.  


=== Projected on-going meeting schedule

The GRI SWG will progress its work through:
Regular online meetings 
Organization of SWG sessions at the OGC Member Meetings and Innovation Days. 

=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially formed. Charter Members are shown on the public SWG page. Extend the table as necessary.

|===
|Name |Organization
| Allan Jamieson    | Ordnance Survey UK
| Ryan Ahola        | Natural Resources Canada / Government of Canada

| Samantha Lavender | Pixalytics
| David Borges      | National Aeronautics and Space Administration (NASA) Committee on earth Observation Satellites (CEOS)

|===

=== Conveners

TbD 

////
Name of individual(s) who started the SWG process. Could be the lead for an RFC submission, an OGC staff person, or an individual who believes it is time for a revision to an adopted Standard.
////

== References

////
Optional list of references.
////
