== Terms and definitions

Carrying Capacity:: An area both suitable and available for human activity based on the state of the ecosystem and competitive pressures for shared resources
Data Cube:: In computer programming contexts, a data cube (or datacube) is a multi-dimensional ("n-D") array of values. Typically, the term data cube is applied in contexts where these arrays are massively larger than the hosting computer's main memory; examples include multi-terabyte/petabyte data warehouses and time series of image data. 
FAIR Climate Service:: Climate resilience information system where the entire architecture is following FAIR principles.
FAIR principle:: Findability, Accessibility, Interoperability, and Reuse of digital assets.
Resilience:: Ability of a system to compensate impacts.
Sentinel (satellite mission):: A series of next-generation Earth observation missions developed by the European Space Agency (ESA), on behalf of the joint ESA/European Commission initiative Copernicus.


=== Abbreviated terms

// Insert abbreviated terms content

ACIS:: Applied Climate Information System
ACDD:: Attribute Convention for Data Discovery
ADES:: Application Deployment and Execution Service
ADS:: Atmosphere Data Store
AR:: Assessment Report
ARD:: Analysis Ready Data
ARDC:: Analysis Ready Data Cube
AP:: Application Package
API:: Application Programming Interface
AWS:: Amazon Web Service
BCSD:: Bias Corrected Spatially Downscaled
BRDF:: Bidirectional Reflectance Distribution Function
CCI:: Climate Change Initiative
CDI:: Combined Drought Indicator
CDR:: Climate Data Record
CDS:: Climate Data Store
CEOS:: Committee on Earth Observation Satellites
CF:: Climate and Forecast
CGMS:: Coordination Group for Meteorological Satellites
CIOOS:: Canadian Integrated Ocean Observing System
CMIP:: Coupled Model Intercomparison Project
CMR:: Common Metadata Repository
CMRA:: Climate Mapping for Resilience and Adaptation
COG:: Cloud Optimized Geotiff
CRIS:: Climate Resilience Information System
CRMA:: Climate Mapping for Resilience and Adaptation 
CSV:: Comma-Separated Values
CWIC:: CEOS WGISS Integrated Catalog
DEM:: Digital Elevation Model
DRI:: Decision Ready Indicator
DSW:: Drought Severity Workflow
DWG:: Domain Working Group
ECMWF:: European Centre for Medium-Range Weather Forecasts
ECV:: Essential Climate Variable
EDR:: Environmental Data Retrieval
EMS:: Exploitation Platform Management Service
EO:: Earth Observation
ER:: Engineering Report
ERA5:: fifth generation ECMWF atmospheric reanalysis of the global climate
ESA:: European Space Agency
ESIP:: Earth Science Information Partners
EUMETSAT::  European Organisation for the Exploitation of Meteorological Satellites
FAIR:: Findability, Accessibility, Interoperability, and Reusability
FAPAR:: Fraction of Absorbed Photosynthetically Active Radiation
FME:: Feature Manipulation Engine
FRP:: Fire Radiant Power
FWI:: Fire Weather Index
GCM:: General Circulation Model
GCOS:: Global Climate Observing System
GDO:: Global Drought Observatory
GDP:: Gross Domestic Product
GML:: Geography Markup Language
GOOS:: Global Ocean Observing System
GRACE:: Gravity Recovery and Climate Experiment
HDF:: Hierarchical Data Format
IFC:: International Finance Corporation
IHO:: International Hydrographic Organization
IMGW:: Polish Institute of Meteorology and Water Management
IOOS:: Integrated Ocean Observing System
IoT:: Internet of Things
IPCC:: Intergovernmental Panel on Climate Change
JSON:: JavaScript Object Notation
KML:: Keyhole Markup Language
LOCA:: Localized Constructed Analogs
MERRA:: Modern Era Retrospective-Analysis for Research and Applications
ML/AI:: Machine Learning / Artificial Intelligence 
MODIS:: Moderate Resolution Imaging Spectroradiometer
MSDI:: Marine Spatial Data Infrastructures
NASA:: National Aeronautics and Space Administration
NCA4:: National Climate Assessment 4
NCAR:: National Center for Atmospheric Research
NDVI:: Normalized Difference Vegetation Index
NDWI:: Normalized Difference Water Index
NetCDF:: Network Common Data Form
NOAA:: National Oceanic and Atmospheric Administration
NRCan:: Natural Resources Canada
OGC:: Open Geospatial Consortium
OGE:: Open Geospatial Engine
OMSv3:: OGC Observations & Measurements 3.0
OPeNDAP:: Open-source Project for a Network Data Access Protocol
OSM:: OpenStreetMap
QGIS:: Quantum Geographic Information System
RCI:: Regional Climate Indicator
RCM:: Regional Climate Model
RCP:: Representative Concentration Pathway
REST:: Representational State Transfer
S3:: Simple Storage Service
SDG:: Sustainable Development Goal
SMA:: Soil Moisture Anomaly
SPEI:: Standardized Precipitation Evapotranspiration Index
SPI:: Standardized Precipitation Index
SQL:: Structured Query Language
SR:: Surface Reflectance
SSL:: Secure Sockets Layer
STAC:: SpatioTemporal Asset Catalogs
THREDDS:: Thematic Real-time Environmental Distributed Data Services
TIE:: Technical Interoperability Experiments
UNFCCC:: United Nations Framework Convention on Climate Change
URL:: Uniform Resource Locator
USGS:: United States Geological Survey
VIIRs:: Visible Infrared Imaging Radiometer Suite
WCS:: Web Coverage Service
WFV:: Wide Field View 
WG Climate:: Joint Working Group on Climate
WGISS:: Working Group on Information Systems and Services
WHI:: Wildland-Human Interface
WMS:: Web Map Service
WPS:: Web Processing Service
WUI:: Wildland-Urban Interface

