
//[[clause-reference]]
== ARD to Decision Ready Indicator (DRI) 


=== Intact Financial Corporation (To be finalized by Intact's push to the main branch)

- Component: 
  * Wildfire hazard map

- Inputs:
  * National fire database polygon data
  * Fire Weather Index (FWI) daily maps
  * Land cover maps
  * Drought conditions
  * Digital Elevation Model (DEM)
  * Population density

- Outputs:
  * Wildfire hazard map, in GeoTiff
  * Regional risk indicators, as tabular output in CSV format
  
- What other component(s) can interact with the component: Intact's component is developed for internal use. It is deployed in highly secured data environments, and as such it cannot readily interact with other components of the pilot. 

- What OGC standards or formats does the component use and produce:
  * GeoTiff
  * NetCDF
  * WPS

==== Company Description 

Intact is the largest provider of Property & Casualty insurance in Canada. Its purpose is to help people, businesses and society prosper in good times and be resilient in bad times. The company has been on the front lines of climate change with our customers for more than a decade – getting them back on track and helping them adapt. As extreme weather is going to get worse over the next decade, Intact intends to double down on adapting to this changing environment and be better prepared for floods, wildfire and extreme heat.


// === Pelagis
=== A federated information model for marine and coastal climate risk indicators

The effects of climate change on coastal environments cannot be understated. As the carrying capacity of our oceans as a carbon sink is reaching its limits, research suggests that an integrated approach to oceans resource management can sustainably meet the needs of global food supplies, offset the rate of ocean acidification, and permanently remove CO2 from the atmosphere. However, accurately measuring both the effect of climate change as well as the mitigation effects of nature-based approaches remains a challenge.

Pelagis is an OceanTech venture located in Nova Scotia, Canada. Our foundation focuses on the application of open geospatial technology and standards designed to promote the sustainable use of our ocean resources.  As a member of the Open Geospatial Consortium, we co-chair the Marine Domain Working Group with a focus on developing a federated model of the marine ecosystem (MSDI) compliant with the suite of OGC specifications and standards.

Pelagis' participation in the Climate Resilience pilot focuses on enhancing our view of a global oceans observation system by combining real-world ground observations with analysis ready datasets. Monitoring aspects of our oceans through both a temporal and spatial continuum while providing traceability through the observations process allows stakeholders to better understand the stressors affecting the health of our oceans and investigate opportunities to mitigate the longer term implications related to climate change.

==== Scope of Work
The project effort centers around 3 key challenges
* the ability to collect data relevant to Climate Resilience;
* the ability to apply the data in a coherent and standardized manner in which to draw out context;
* and the ability to impart insight to community members and stakeholders so as to identify, anticipate and mitigate the effects of climate change across both local and international boundaries.

Each of these activities aligns with the best practices and standards of the OGC and are used as input to the MarineDWG MSDI reference model.

==== Approach
The approach to address the needs for the shared use of Prelagis ocean resources is to make Marine Spatial Planning a core foundation on which to build out vertical applications. Prelagis platform is based on a federated information model represented as a unified social graph. This provides a decentralized approach towards designing various data streams each represented by their well-known and/or standardized model. To date, service layers based on the OGC standards for Feature, Observations & Measurements, and Sensors APIs have been developed and extended for adoption within the marine domain model. Previous work provides for data discovery and processing of features based on the IHO S-100 standard (Marine Protected Areas, Marine Traffic Management, …); NOAA open data pipelines for major weather events (Hurricane Tracking, Ocean Drifters, Saildrones …); as well as connected observation systems as provided by IOOS and its Canadian variant, CIOOS.

[#img-pelagis-architecture]
.Architecture
image::pelagis.architecture(1).svg[Pelagis-architecture, ,align=center, width=600]



=== ECMWF - Copernicus (will be integrated with INTRODUCTION section)

- Component: Copernicus services.

- Outputs: Copernicus Services, including Climate Data Store (CDS) https://cds.climate.copernicus.eu/ and Atmosphere Data Store (ADS) https://ads.atmosphere.copernicus.eu/. 

- What other component(s) can interact with the component: CDS and ADS provide access to data via different interfaces: UI and API. It also offers a toolbox with a set of expert libraries to perform advanced operations on the available data. CDS and ADS catalogue metadata is also accessible via standard CSW. https://cds.climate.copernicus.eu/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

- What OGC standards or formats does the component use and produce: 
  * CDS and ADS catalogues exposed via CSW. 
  * Access to ESGF datasets via WPS. 
  * WMS is offered in some published applications. 
  * CADS 2.0 (under construction) will implement OGC APIs.



