
== Future Work

// Sam - I've written with some initial suggestions based on the text that was here and from reading the introductory sections

Being the first OGC Climate Pilot, there has been significant underpinning work on the component elements that has supported an improved understanding of what is currently possible and what needs to be developed. Future pilots will focus on supporting the filling-in of identified gaps and definition of best practices guidelines to support and enable broader international partnerships.

During the pilot, participants agreed to the following items were specific actions where future work would be needed:

- Further integration of the contributor components so that full workflows, from raw data to visualization and communication, can be tested.
- Exploring additional scenario tests including comparisons with historical norms, e.g. calculating the difference between historical maximum temperatures and projected maximum temperatures. 
- More analysis with higher resolution time steps - weekly and daily. At the outset monthly time steps have been used to make it easier to prototype workflows. Daily time step computations will take significantly more processing time.
- 



