
== Recommendations for future climate resilience pilots [[Chapter_Recommendations]]

Based on the experiences of this first Climate Resilience Pilot, the lessons learned could result in a refined design of the upcoming future pilot focusing on climate resilience to address the most relevant challenges. Within these efforts, the OGC Climate Resilience Community has been growing and is bringing together decision-makers, scientists, policymakers, data providers, software developers, and service providers. This includes scientists, decision-makers, city managers, politicians, and last but not least, it includes every one of us.
Thematic aspects: Climate change resilience to the triple crisis
The current climate resilience pilot had a focus on climate change-related phenomena including, while the ongoing international discussion is moving toward the holistic perspective of the triple crisis, where the triple is targeting Climate Change and also the loss of Biodiversity and Pollution. It is recommended to address the upcoming climate resilience pilot in line with the technical challenges of this triple crisis and select doable aspects according. As a result of the closing workshop at the OGC Member Meeting in Huntsville, the thematic areas of upcoming work should be focussing on precipitation with aspects of their extremes causing disasters. This will be phenomena of inundations and floods in case of extremely high amounts of precipitation as well as droughts and desertification in case of dryness anomalies. Both cases can lead to land degradation which should be considered in line with climate resilience and loss of biodiversity. To cover the third aspect of the triple crisis, in terms of pollution, Air pollution, and emissions of greenhouse gasses (GHG) have been identified as important issues to tackle in various ways. Either by enhancing information production out of the monitoring systems and services with respect to the UN reporting requirements of the upcoming UN Global Stocktake underpinning the climate actions of the nations in line with their national determined contributions (NDC) to reduce GHG emissions.  A further aspect on GHG emission is the feedback loop to the change in precipitation patterns and land use change, which is affecting the soil carbon content, as one of the indicators of land degradation. Changes in soil carbon content are also resulting due to the melting processes of the permafrost affecting very large regions in the upper northern hemisphere like the Canadian and the Russian tundra.

Focussing on regions, the challenges are located in mountainous areas, small islands as well as hyper-arid areas. This is related to the complexity of the very small scale of the natural climatic phenomena. The complexity if going to be fostered if change of land use is been taken into account. 


The climate resilience pilot was running in parallel with other pilots and had many touchpoints with the disaster pilot. Important lessons learned from the growth of the OGC climate resilience community, and the common understanding of phenomena in line with climate resilience versus disaster resilience are guiding the recommendation to merge both pilot lines. 
A future climate resilience pilot disaster aspects will be respected since the technical Climate Resilience Information Systems (CRIS) and the aspects of FAIR Climate services establish modular climate application packages which are interoperable with each other and are guided to the same technical principles and tools.

