
== Recommendations for future climate resilience pilots [[Chapter_Recommendations]]

Based on the experiences of this first Climate Resilience Pilot, the lessons learned could result in a refined design of the upcoming future pilot focusing on climate resilience to address the most relevant challenges. Within these efforts, the OGC Climate Resilience Community has been growing and is bringing together decision-makers, scientists, policymakers, data providers, software developers, and service providers. This includes scientists, decision-makers, city managers, politicians, and last but not least, it includes every one of us.
Thematic aspects: Climate change resilience to the triple crisis
The current climate resilience pilot had a focus on climate change-related phenomena including, while the ongoing international discussion is moving toward the holistic perspective of the triple crisis, where the triple is targeting Climate Change and also the loss of Biodiversity and Pollution. It is recommended to address the upcoming climate resilience pilot in line with the technical challenges of this triple crisis and select doable aspects according. As a result of the closing workshop at the OGC Member Meeting in Huntsville, the thematic areas of upcoming work should be focussing on precipitation with aspects of their extremes causing disasters. This will be phenomena of inundations and floods in case of extremely high amounts of precipitation as well as droughts and desertification in case of dryness anomalies. Both cases can lead to land degradation which should be considered in line with climate resilience and loss of biodiversity. To cover the third aspect of the triple crisis, in terms of pollution, Air pollution, and emissions of greenhouse gasses (GHG) have been identified as important issues to tackle in various ways. Either by enhancing information production out of the monitoring systems and services with respect to the UN reporting requirements of the upcoming UN Global Stocktake underpinning the climate actions of the nations in line with their national determined contributions (NDC) to reduce GHG emissions.  A further aspect on GHG emission is the feedback loop to the change in precipitation patterns and land use change, which is affecting the soil carbon content, as one of the indicators of land degradation. Changes in soil carbon content are also resulting due to the melting processes of the permafrost affecting very large regions in the upper northern hemisphere like the Canadian and the Russian tundra.

Focussing on regions, the challenges are located in mountainous areas, small islands as well as hyper-arid areas. This is related to the complexity of the very small scale of the natural climatic phenomena. The complexity if going to be fostered if change of land use is been taken into account. 


The climate resilience pilot was running in parallel with other pilots and had many touchpoints with the disaster pilot. Important lessons learned from the growth of the OGC climate resilience community, and the common understanding of phenomena in line with climate resilience versus disaster resilience are guiding the recommendation to merge both pilot lines. 
A future climate resilience pilot disaster aspects will be respected since the technical Climate Resilience Information Systems (CRIS) and the aspects of FAIR Climate services establish modular climate application packages which are interoperable with each other and are guided to the same technical principles and tools.


=== Technical aspects: Climate resilience information systems towards FAIR Climate services 

Issues around the delivery of climate information to support adaptation decisions to facilitate the difficult and time-consuming work of climate service centers. These centers may have a local, regional or international scope, but typically act as boundary organizations, connecting clients to climate science data and expertise. As demand increases for climate products, climate service centers are pressured to develop and deploy IT systems to access and process climate data more efficiently and expand the range and complexity of services they deliver. Although climate adaptation challenges vary across regions, data processing workflows are very similar and could benefit from shared information systems. Land Degradation Neutrality (LDN) and climate resilience are strongly related in the scientific phenomenon as well the technical applications regarding the value chain from raw data to information and knowledge. In both cases, similar approaches have been developed concerning data handling in datacubes, analysis-ready data (ARD) up to the decision-ready indicators (DRI). Agreeing on standards regarding DataCube, ARD, and DRI is enabling a better linkage between the information exchange within the UN climate policy frame and beyond.


Interoperability studies and gap analysis of data sources and infrastructures. Here especially the Copernicus Climate Change Service (C3S) with its underpinned Climate Data Store (CDS), which had been currently renewed and moved into higher interoperability. A dedicated gap analysis and interoperability experiment concerning the usability of the C3S technical services in line with existing other climate resilience information systems would be a useful step toward the vision of global collaborative solutions. In this aspect the concept of FAIR Climate services can be refined, extended and properly documented.


It is further recommended to further lower the barriers for experts who want to spin off climate resilience information systems for their specific use cases and needs. As demonstrated in the pilot, modular chaining of components are the recommended approach to design the architecture, with climate application packages with are interoperable with each other following the FAIR Climate Services principles. There are existing utilities (birdhouse approach demonstrated in this pilot) helping developers to establish climate application packages that need to be further developed and improved for better usability. Equality to climate application packages, the concept of LDN value chain is following the same approach of modular interoperable components where interoperability can be enhanced. 

It is further recommended, that aspects of data visualization and the use of case-specific simulations need to be emphasized. Especially the small-scale 3D visualizations including realistic digital twins of vegetation, and respective trees in digital twins of urban areas are recommended to be enhanced in the future. The pilot has shown the power of artificial intelligence to establish realistic simulations of use cases under different climatic scenarios. Enhancing the technology behind, and establishing the data visualisation and simulation for specific use-cases, political decisions or socioeconomic scenarios with respect to future climate projections would be a step forward in closing the gap between existing climate information and implemented climate action. 

