
== Recommendations for future climate resilience pilots [[Chapter_Recommendations]]

Based on the experiences of this first Climate Resilience Pilot, the lessons learned could result in a refined design of the upcoming future pilot focusing on climate resilience to address the most relevant challenges. Within these efforts, the OGC Climate Resilience Community has been growing and is bringing together decision-makers, scientists, policymakers, data providers, software developers, and service providers. This includes scientists, decision-makers, city managers, politicians, and last but not least, it includes every one of us.

=== Thematic aspects: Climate change resilience to the triple crisis

The current climate resilience pilot had focused on climate change-related phenomena, while the ongoing international discussion is moving toward the holistic perspective of the triple crisis, where the triple is targeting Climate Change, the loss of Biodiversity, and Pollution. Therefore, it is recommended to address these within the upcoming climate resilience pilot, in line with the technical challenges of this triple crisis and selecting doable aspects according. As a result of the closing workshop at the OGC Member Meeting in Huntsville, the thematic areas of upcoming work should focus on precipitation with extreme aspects extremes causing disasters: floods in case of extremely high amounts of precipitation and droughts and desertification in case of dryness anomalies. Both cases can lead to land degradation, which should be considered inline with climate resilience and loss of biodiversity. 

To cover the third aspect of the triple crisis, pollution, air pollution and emissions of greenhouse gasses (GHG) have been identified as important issues to tackle in various ways by enhancing information production out of the monitoring systems and services with respect to the UN reporting requirements of the upcoming UN Global Stocktake underpinning the climate actions of the nations inline with their national determined contributions (NDC) to reduce GHG emissions. A further aspect of GHG emission is the feedback loop to the change in precipitation patterns and land use change, which is affecting soil carbon content, as one of the indicators of land degradation. Changes in soil carbon content are also caused by to melting of the permafrost affecting very large regions in the upper northern hemisphere such as the Canadian and the Russian tundras.

Focusing on regions, the challenges are located in mountainous areas, small islands, and hyper-arid areas, which is related to the complexity of the very small scale of natural climatic phenomena. The complexity is going to be fostered if land use change is been taken into account. 


The climate resilience pilot ran in parallel with other pilots and had many touch points with the disaster pilot. Important lessons learned from the growth of the OGC climate resilience community, and the common understanding of phenomena inline with climate resilience versus disaster resilience are guiding the recommendation to merge both pilot lines. 

A future climate resilience pilot with disaster aspects will be respected since the technical Climate Resilience Information Systems (CRIS) and the aspects of FAIR Climate services establish modular climate application packages which are interoperable with each other and are guided by the same technical principles and tools.


=== Technical aspects: Climate resilience information systems towards FAIR Climate services 

Issues around the delivery of climate information to support adaptation decisions to facilitate the difficult and time-consuming work of climate service centers. These centers may have a local, regional, or international scope, but typically act as boundary organizations, connecting clients to climate science data and expertise. As demand increases for climate products, climate service centers are pressured to develop and deploy IT systems to access and process climate data more efficiently and expand the range and complexity of services delivered. Although climate adaptation challenges vary across regions, data processing workflows are very similar and could benefit from shared information systems. Land Degradation Neutrality (LDN) and climate resilience are strongly related to the scientific phenomenon as well the technical applications regarding the value chain from raw data to information and knowledge. In both cases, similar approaches have been developed concerning data handling in datacubes and analysis-ready data (ARD) up to the decision-ready indicators (DRI). Agreeing on standards regarding DataCube, ARD, and DRI would enable a better linkage between the information exchange within the UN climate policy frame and beyond.

=== Interoperability studies and gap analysis of data sources and infrastructures

Here, especially, the Copernicus Climate Change Service (C3S) with its underpinned Climate Data Store (CDS) is an example that has been renewed and moved into higher interoperability. A dedicated gap analysis and interoperability experiment concerning the usability of the C3S technical services inline with existing other climate resilience information systems would be a useful step towards the vision of global collaborative solutions. In this aspect, the concept of FAIR Climate services can be refined, extended, and properly documented.

It is further recommended to continue lowering the barriers for experts who want to spin off climate resilience information systems for their specific use cases and needs. As demonstrated in the pilot, the modular chaining of components is the recommended approach to design the architecture, with climate application packages being interoperable with each other and following the FAIR Climate Services principles. There are existing utilities (birdhouse approach demonstrated in this pilot) helping developers to establish climate application packages that need to be further developed and improved for better usability. Equality to climate application packages, the concept of LDN value chain, is following the same approach of modular interoperable components where interoperability can be enhanced. 

It is further recommended, that aspects of data visualization and the use of case-specific simulations need to be emphasized. Especially the small-scale 3D visualizations, including realistic digital twins of vegetation, and respective trees in digital twins of urban areas are recommended for enhancement in the future. The pilot has shown the power of artificial intelligence to establish realistic simulations of use cases under different climatic scenarios. Enhancing the technology behind, and establishing the data visualization and simulation for, specific use-cases, political decisions or socioeconomic scenarios with respect to future climate projections would be a step forward in closing the gap between existing climate information and implemented climate action. 


=== Climate Service Consultation aspects: Communication to Stakeholders

The upcoming CRP24 should have a user-centric approach, to tailor the data products and application packages for optimization to the user needs and requirements. The existing OGC stakeholder community should be more strongly included during the pilot execution to tailor the value chain from raw data to information according to the stakeholder requirements. It is recommended to design the OGC pilots with activities addressing potential stakeholders to grow the OGC Stakeholder community as well as to understand their requirements and address data products and tools related to their needs, further bridging the gap of scientific knowledge to policy-driven climate action. The huge amount of knowledge about climate change and its potential impact and the relatively low socio-economic change, called the knowing-doing-gap, can be addressed in future work. The improvement and incorporation of the communication aspects explored in the current pilot should be emphasized and enhanced with existing technologies, especially simulations and data visualization. Also, the good practice guidance of the UNCCD is proposing ‘decision trees’ for end users to identify the most reliable data that exist for a region. 

OGC needs to continue to move towards non-technical communication; breaking down the very technical engineering reports into non-technical content, such as animation videos. Especially for the domain of climate and disaster resilience, the understanding of the principle importance for the work concerning FAIR Climate services is essential to be presented in other formats than only engineering reports. Besides explanation videos, capacity building can be done with modules in e-learning platforms that are currently being established in OGC. Future pilots should output tutorials and training materials to lower the barriers for developers by spinning off their applications based on good practice guidelines, tutorials, and e-learning modules. In this context, established running applications can be promoted over the upcoming open science persistent demonstrator. It is recommended that OGC tailor capacity-building material in formats that are exchangeable with other open knowledge platforms like the GEO Knowledge hub. 
A further aspect of capacity building and reaching out is to move the upcoming work into multiple languages. The animation video of this pilot has already been produced in four languages; in addition to English, it is available in French, Spanish, and Chinese. Upcoming future work should not be restricted to only English, but should target to other languages as well. 
